package com.lockOnActive;
import com.drools.model.Person
dialect  "mvel"

rule "lockOnActiceRules-1"
    when
        $p : Person(age > 10)
    then
        $p.setAge(9);
        update($p)
        System.out.println("lockOnActiceRules-1 被执行");
end

rule "lockOnActiceRules-2"
    lock-on-active true
    when
        $p : Person(age < 10)
    then
        System.out.println("lockOnActiceRules-2 被执行");
end
