package com.insertRule;
import com.drools.model.Person
dialect  "mvel"

rule "insertRule-1"
    when
    then
        System.out.println("insertRule-1 触发了");
        Person p = new Person();
        p.setAge(20);
        insert(p);
end

rule "insertRule-2"
//    lock-on-active true
    when
        $p : Person(age == 20)
    then
        System.out.println("insertRule-2 触发了，age=" + $p.getAge());
end

